# Generated by Django 5.2.5 on 2025-10-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Card title in English', max_length=200, verbose_name='Title (English)')),
                ('image_url', models.URLField(help_text='Cloudinary or external image URL', verbose_name='Image URL')),
                ('route', models.CharField(help_text='Angular route (e.g., /platforms/corporate-business)', max_length=100, verbose_name='Route')),
                ('title_bg', models.CharField(help_text='Заглавие на картата на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this card on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Card',
                'verbose_name_plural': 'Platform Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
