# Generated by Django 5.2.5 on 2025-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcard',
            name='hover_color',
            field=models.CharField(default='#4F46E5', help_text='Hex color for hover effect (e.g., #4F46E5)', max_length=7, verbose_name='Hover Color'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item1_bg',
            field=models.CharField(default='', help_text='Първи елемент при hover', max_length=200, verbose_name='Елемент 1 (Български)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item1_en',
            field=models.CharField(default='', help_text='First item text on hover', max_length=200, verbose_name='Item 1 (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item2_bg',
            field=models.CharField(blank=True, help_text='Втори елемент при hover (опционален)', max_length=200, verbose_name='Елемент 2 (Български)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item2_en',
            field=models.CharField(blank=True, help_text='Second item text on hover (optional)', max_length=200, verbose_name='Item 2 (English)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item3_bg',
            field=models.CharField(blank=True, help_text='Трети елемент при hover (опционален)', max_length=200, verbose_name='Елемент 3 (Български)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item3_en',
            field=models.CharField(blank=True, help_text='Third item text on hover (optional)', max_length=200, verbose_name='Item 3 (English)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item4_bg',
            field=models.CharField(blank=True, help_text='Четвърти елемент при hover (опционален)', max_length=200, verbose_name='Елемент 4 (Български)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='item4_en',
            field=models.CharField(blank=True, help_text='Fourth item text on hover (optional)', max_length=200, verbose_name='Item 4 (English)'),
        ),
    ]
