# Generated by Django 5.2.5 on 2025-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0002_platformcard_hover_color_platformcard_item1_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Slide title in English', max_length=200, verbose_name='Title (English)')),
                ('description_en', models.TextField(help_text='Slide description in English', verbose_name='Description (English)')),
                ('button_text_en', models.CharField(help_text='Call-to-action button text in English', max_length=100, verbose_name='Button Text (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на слайда на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('description_bg', models.TextField(help_text='Описание на слайда на български', verbose_name='Описание (Български)')),
                ('button_text_bg', models.CharField(help_text='Текст на бутона на български', max_length=100, verbose_name='Текст на бутон (Български)')),
                ('button_link', models.CharField(help_text='URL or Angular route (e.g., /contact or https://example.com)', max_length=200, verbose_name='Button Link')),
                ('background_image', models.URLField(help_text='Cloudinary or external image URL for slide background', verbose_name='Background Image URL')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in the hero slider', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
