# Generated by Django 5.2.5 on 2025-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0003_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text="Achievement title in English (e.g., 'Completed Projects')", max_length=200, verbose_name='Title (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на постижението на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('count', models.CharField(help_text="Display value (e.g., '10 000+', '200+', '70M+')", max_length=50, verbose_name='Count/Value')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this achievement on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Our Customers', help_text='Main section title in English', max_length=200, verbose_name='Section Title (English)')),
                ('subtitle_en', models.TextField(help_text='Section subtitle/description in English', verbose_name='Section Subtitle (English)')),
                ('title_bg', models.CharField(default='Нашите клиенти', help_text='Главно заглавие на секцията на български', max_length=200, verbose_name='Заглавие на секция (Български)')),
                ('subtitle_bg', models.TextField(help_text='Подзаглавие/описание на секцията на български', verbose_name='Подзаглавие на секция (Български)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customers Section Header',
                'verbose_name_plural': 'Customers Section Header',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the partner/client company', max_length=200, verbose_name='Partner Name')),
                ('logo_url', models.URLField(help_text='URL to partner logo (Cloudinary or external)', verbose_name='Logo URL')),
                ('order', models.IntegerField(default=0, help_text='Display order in carousel', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this partner logo in the carousel', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
