# Generated by Django 5.2.5 on 2025-10-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0004_achievement_customerssection_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Customers Section - Achievement', 'verbose_name_plural': 'Customers Section - Achievements'},
        ),
        migrations.AlterModelOptions(
            name='customerssection',
            options={'verbose_name': 'Customers Section - Header', 'verbose_name_plural': 'Customers Section - Header'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Customers Section - Partner Logo', 'verbose_name_plural': 'Customers Section - Partner Logos'},
        ),
    ]
