# Generated by Django 5.2.5 on 2025-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0005_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Case study title in English', max_length=200, verbose_name='Title (English)')),
                ('category_en', models.CharField(help_text="Category/industry in English (e.g., 'Financial Services')", max_length=100, verbose_name='Category (English)')),
                ('button_text_en', models.CharField(default='Read More', help_text='Call-to-action button text in English', max_length=100, verbose_name='Button Text (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на case study на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('category_bg', models.CharField(help_text='Категория/индустрия на български', max_length=100, verbose_name='Категория (Български)')),
                ('button_text_bg', models.CharField(default='Прочети повече', help_text='Текст на бутона на български', max_length=100, verbose_name='Текст на бутон (Български)')),
                ('button_link', models.CharField(help_text='URL or Angular route (e.g., /case-studies/project-name)', max_length=200, verbose_name='Button Link')),
                ('background_image', models.URLField(help_text='Cloudinary or external image URL for slide background', verbose_name='Background Image URL')),
                ('overlay_image', models.URLField(help_text='Cloudinary or external image URL for overlay/foreground', verbose_name='Overlay Image URL')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this case study in the slider', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Generix Section - Case Study',
                'verbose_name_plural': 'Why Generix Section - Case Studies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyGenerixSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='What clients say about us', help_text='Main section title in English', max_length=200, verbose_name='Section Title (English)')),
                ('paragraph1_en', models.TextField(help_text='First paragraph in English', verbose_name='Paragraph 1 (English)')),
                ('paragraph2_en', models.TextField(help_text='Second paragraph in English', verbose_name='Paragraph 2 (English)')),
                ('paragraph3_en', models.TextField(help_text='Third paragraph (before View All button) in English', verbose_name='Paragraph 3 (English)')),
                ('title_bg', models.CharField(default='Какво казват клиентите за нас', help_text='Главно заглавие на секцията на български', max_length=200, verbose_name='Заглавие на секция (Български)')),
                ('paragraph1_bg', models.TextField(help_text='Първи параграф на български', verbose_name='Параграф 1 (Български)')),
                ('paragraph2_bg', models.TextField(help_text='Втори параграф на български', verbose_name='Параграф 2 (Български)')),
                ('paragraph3_bg', models.TextField(help_text='Трети параграф (преди бутона View All) на български', verbose_name='Параграф 3 (Български)')),
                ('button_text_en', models.CharField(default='View All', help_text='View All button text in English', max_length=100, verbose_name='Button Text (English)')),
                ('button_text_bg', models.CharField(default='Виж всички', help_text='Текст на бутона View All на български', max_length=100, verbose_name='Текст на бутон (Български)')),
                ('button_link', models.CharField(default='/about', help_text='URL or Angular route (e.g., /about)', max_length=200, verbose_name='Button Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Generix Section - Content',
                'verbose_name_plural': 'Why Generix Section - Content',
            },
        ),
    ]
