# Generated by Django 5.2.5 on 2025-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0006_casestudyslide_whygenerixsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyslide',
            name='label_bg',
            field=models.CharField(default='Казус', help_text="Малък текст над заглавието на български (напр. 'Казус', 'История на успеха')", max_length=50, verbose_name='Етикет (Български)'),
        ),
        migrations.AddField(
            model_name='casestudyslide',
            name='label_en',
            field=models.CharField(default='Case Study', help_text="Small label text above title in English (e.g., 'Case Study', 'Success Story')", max_length=50, verbose_name='Label/Badge (English)'),
        ),
    ]
