# Generated by Django 5.2.5 on 2025-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0007_casestudyslide_label_bg_casestudyslide_label_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyslide',
            name='label_bg',
        ),
        migrations.RemoveField(
            model_name='casestudyslide',
            name='label_en',
        ),
        migrations.AlterField(
            model_name='casestudyslide',
            name='category_bg',
            field=models.CharField(help_text="Категория/индустрия на български (напр. 'Казус', 'История на успеха')", max_length=100, verbose_name='Категория (Български)'),
        ),
        migrations.AlterField(
            model_name='casestudyslide',
            name='category_en',
            field=models.CharField(help_text="Category/industry in English (e.g., 'Case Study', 'Success Story')", max_length=100, verbose_name='Category (English)'),
        ),
    ]
