# Generated by Django 5.2.5 on 2025-10-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0008_remove_case_study_label_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_en', models.TextField(help_text='Main testimonial quote in English', verbose_name='Quote (English)')),
                ('quote_bg', models.TextField(help_text='Главен цитат на български', verbose_name='Цитат (Български)')),
                ('author_name_en', models.CharField(help_text="Author's full name in English", max_length=200, verbose_name='Author Name (English)')),
                ('author_name_bg', models.CharField(help_text='Пълно име на автора на български', max_length=200, verbose_name='Име на автор (Български)')),
                ('author_title_en', models.CharField(help_text="Author's position/title in English (e.g., 'CEO & Founder')", max_length=200, verbose_name='Author Title (English)')),
                ('author_title_bg', models.CharField(help_text='Позиция/титла на автора на български', max_length=200, verbose_name='Позиция (Български)')),
                ('author_quote_en', models.TextField(help_text='Short quote from author in English', verbose_name='Author Quote (English)')),
                ('author_quote_bg', models.TextField(help_text='Кратък цитат от автора на български', verbose_name='Цитат на автор (Български)')),
                ('author_image', models.URLField(help_text="URL to author's profile image", verbose_name='Author Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Section - Testimonial',
                'verbose_name_plural': 'About Us Section - Testimonial',
            },
        ),
    ]
