# Generated by Django 5.2.5 on 2025-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0009_add_about_us_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for identification (e.g., 'About Page CTA', 'Services CTA')", max_length=100, verbose_name='CTA Name')),
                ('title_en', models.CharField(help_text='CTA title in English', max_length=200, verbose_name='Title (English)')),
                ('description_en', models.TextField(help_text='CTA description in English', verbose_name='Description (English)')),
                ('button_text_en', models.CharField(default='Contact Us', help_text='Button text in English', max_length=100, verbose_name='Button Text (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на CTA на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('description_bg', models.TextField(help_text='Описание на CTA на български', verbose_name='Описание (Български)')),
                ('button_text_bg', models.CharField(default='Свържете се с нас', help_text='Текст на бутона на български', max_length=100, verbose_name='Текст на бутон (Български)')),
                ('button_link', models.CharField(default='/contact', help_text='URL or Angular route (e.g., /contact)', max_length=200, verbose_name='Button Link')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this CTA on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call-to-Action (Gradient)',
                'verbose_name_plural': 'Call-to-Actions (Gradient)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='CTA title in English', max_length=200, verbose_name='Title (English)')),
                ('button_text_en', models.CharField(default='Contact Us', help_text='Button text in English', max_length=100, verbose_name='Button Text (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на CTA на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('button_text_bg', models.CharField(default='Свържете се с нас', help_text='Текст на бутона на български', max_length=100, verbose_name='Текст на бутон (Български)')),
                ('button_link', models.CharField(default='/contact', help_text='URL or Angular route (e.g., /contact)', max_length=200, verbose_name='Button Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page - CTA White',
                'verbose_name_plural': 'Home Page - CTA White',
            },
        ),
    ]
