# Generated by Django 5.2.5 on 2025-10-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0010_add_cta_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcard',
            name='is_platform',
            field=models.BooleanField(default=True, help_text='True = Platform with features page, False = Simple card (e.g., CTA)', verbose_name='Is Platform'),
        ),
        migrations.CreateModel(
            name='PlatformFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Feature title in English', max_length=200, verbose_name='Title (English)')),
                ('description_en', models.TextField(help_text='Feature description in English', verbose_name='Description (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на функционалността на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('description_bg', models.TextField(help_text='Описание на функционалността на български', verbose_name='Описание (Български)')),
                ('icon', models.ImageField(help_text='Icon image for this feature', upload_to='platform_features/', verbose_name='Icon')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this feature on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(help_text="Select platform (only cards marked as 'Platform')", limit_choices_to={'is_platform': True}, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api_generix.platformcard', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Platform Feature',
                'verbose_name_plural': 'Platform Features',
                'ordering': ['platform', 'order', 'id'],
                'unique_together': {('platform', 'order')},
            },
        ),
    ]
