# Generated by Django 5.2.5 on 2025-10-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0011_add_platform_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfeature',
            name='icon',
        ),
        migrations.AddField(
            model_name='platformfeature',
            name='icon_url',
            field=models.URLField(default='', help_text='URL to icon (Cloudinary SVG or image URL)', verbose_name='Icon URL'),
            preserve_default=False,
        ),
    ]
