# Generated by Django 5.2.5 on 2025-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0012_change_platform_feature_icon_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcard',
            name='hero_title_bg',
            field=models.CharField(blank=True, help_text='Заглавие в hero секцията на страницата (само за платформи)', max_length=200, verbose_name='Hero заглавие (Български)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='Platform page hero title (only for platforms)', max_length=200, verbose_name='Hero Title (English)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='subtitle_bg',
            field=models.TextField(blank=True, help_text='Подзаглавие/описание на страницата (само за платформи)', verbose_name='Подзаглавие (Български)'),
        ),
        migrations.AddField(
            model_name='platformcard',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Platform page subtitle/description (only for platforms)', verbose_name='Subtitle (English)'),
        ),
    ]
