# Generated by Django 5.2.5 on 2025-10-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0013_add_platform_hero_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_en', models.CharField(help_text='Main hero title for About page in English', max_length=200, verbose_name='Hero Title (English)')),
                ('hero_title_bg', models.CharField(help_text='Главно hero заглавие за About страница на български', max_length=200, verbose_name='Hero заглавие (Български)')),
                ('paragraph1_en', models.TextField(help_text='First paragraph of content in English', verbose_name='Paragraph 1 (English)')),
                ('paragraph1_bg', models.TextField(help_text='Първи параграф на съдържанието на български', verbose_name='Параграф 1 (Български)')),
                ('paragraph2_en', models.TextField(help_text='Second paragraph of content in English', verbose_name='Paragraph 2 (English)')),
                ('paragraph2_bg', models.TextField(help_text='Втори параграф на съдържанието на български', verbose_name='Параграф 2 (Български)')),
                ('paragraph3_en', models.TextField(help_text='Third paragraph of content in English', verbose_name='Paragraph 3 (English)')),
                ('paragraph3_bg', models.TextField(help_text='Трети параграф на съдържанието на български', verbose_name='Параграф 3 (Български)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page - Hero & Content',
                'verbose_name_plural': 'About Page - Hero & Content',
            },
        ),
    ]
