# Generated by Django 5.2.5 on 2025-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0014_add_about_page_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformsSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Our Platforms', help_text='Platforms section title in English', max_length=200, verbose_name='Title (English)')),
                ('subtitle_en', models.TextField(help_text='Platforms section subtitle in English', verbose_name='Subtitle (English)')),
                ('title_bg', models.CharField(default='Нашите платформи', help_text='Заглавие на секцията с платформи на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('subtitle_bg', models.TextField(help_text='Подзаглавие на секцията с платформи на български', verbose_name='Подзаглавие (Български)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platforms Section - Header',
                'verbose_name_plural': 'Platforms Section - Header',
            },
        ),
    ]
