# Generated by Django 5.2.5 on 2025-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0015_add_platforms_section_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary_dark', models.CharField(default='#0A1F44', help_text='Hex color (e.g., #0A1F44) - Тъмносиньо за фон и заглавия', max_length=7, verbose_name='Primary Dark Color')),
                ('color_primary_light', models.CharField(default='#00B2FF', help_text='Hex color (e.g., #00B2FF) - Синьо-зелено за акценти и бутони', max_length=7, verbose_name='Primary Light Color')),
                ('color_background', models.CharField(default='#F5F7FA', help_text='Hex color (e.g., #F5F7FA) - Светлосиво за фон на секции', max_length=7, verbose_name='Background Color')),
                ('color_text', models.CharField(default='#3C3C3C', help_text='Hex color (e.g., #3C3C3C) - Тъмно сиво за основен текст', max_length=7, verbose_name='Text Color')),
                ('color_white', models.CharField(default='#FFFFFF', help_text='Hex color (e.g., #FFFFFF) - Бяло за фон и контраст', max_length=7, verbose_name='White Color')),
                ('color_accent', models.CharField(default='#00B2FF', help_text='Hex color (e.g., #00B2FF) - Accent color', max_length=7, verbose_name='Accent Color')),
                ('color_accent_hover', models.CharField(default='#0095D9', help_text='Hex color (e.g., #0095D9) - Darker shade for hover', max_length=7, verbose_name='Accent Hover Color')),
                ('color_hover_indigo', models.CharField(default='#4F46E5', help_text='Hex color (e.g., #4F46E5) - Indigo for first platform card', max_length=7, verbose_name='Hover Indigo')),
                ('color_hover_pink', models.CharField(default='#EC4899', help_text='Hex color (e.g., #EC4899) - Pink for second platform card', max_length=7, verbose_name='Hover Pink')),
                ('color_hover_cyan', models.CharField(default='#06B6D4', help_text='Hex color (e.g., #06B6D4) - Cyan for third platform card', max_length=7, verbose_name='Hover Cyan')),
                ('color_success', models.CharField(default='#10b981', help_text='Hex color (e.g., #10b981) - Green for success messages', max_length=7, verbose_name='Success Color')),
                ('color_warning', models.CharField(default='#f59e0b', help_text='Hex color (e.g., #f59e0b) - Orange for warnings', max_length=7, verbose_name='Warning Color')),
                ('color_error', models.CharField(default='#ef4444', help_text='Hex color (e.g., #ef4444) - Red for errors', max_length=7, verbose_name='Error Color')),
                ('color_info', models.CharField(default='#3b82f6', help_text='Hex color (e.g., #3b82f6) - Blue for info messages', max_length=7, verbose_name='Info Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
