# Generated by Django 5.2.5 on 2025-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0016_add_theme_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='color_border_gray',
            field=models.CharField(default='#e0e0e0', help_text='Hex color (e.g., #e0e0e0) - Gray border color', max_length=7, verbose_name='Gray Border'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_gray_dark',
            field=models.CharField(default='#555555', help_text='Hex color (e.g., #555555) - Dark gray', max_length=7, verbose_name='Dark Gray'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_gray_light',
            field=models.CharField(default='#666666', help_text='Hex color (e.g., #666666) - Light gray text', max_length=7, verbose_name='Light Gray'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_gray_medium',
            field=models.CharField(default='#999999', help_text='Hex color (e.g., #999999) - Medium gray', max_length=7, verbose_name='Medium Gray'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_neutral',
            field=models.CharField(default='#F5F7FA', help_text='Hex color (e.g., #F5F7FA) - Neutral background', max_length=7, verbose_name='Neutral Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_text_dark',
            field=models.CharField(default='#333333', help_text='Hex color (e.g., #333333) - Dark text for headings', max_length=7, verbose_name='Dark Text Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_text_secondary',
            field=models.CharField(default='#6B7280', help_text='Hex color (e.g., #6B7280) - Secondary text color', max_length=7, verbose_name='Secondary Text Color'),
        ),
    ]
