# Generated by Django 5.2.5 on 2025-11-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0017_themesettings_color_border_gray_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='color_background_secondary',
            field=models.CharField(default='#f5f2f2', help_text='Hex color (e.g., #f5f2f2) - Alternative light background', max_length=7, verbose_name='Secondary Background'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_black',
            field=models.CharField(default='#000000', help_text='Hex color (e.g., #000000) - Pure black for text and elements', max_length=7, verbose_name='Black Color'),
        ),
    ]
