# Generated by Django 5.2.5 on 2025-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0018_themesettings_color_background_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='color_background_alt',
            field=models.CharField(default='#E5E7EB', help_text='Hex color (e.g., #E5E7EB) - Alternative light gray background', max_length=7, verbose_name='Alternative Background'),
        ),
    ]
