# Generated by Django 5.2.5 on 2025-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0020_contactpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(help_text='URL to company/partner logo image', verbose_name='Logo URL')),
                ('name_en', models.CharField(help_text='Person or company name in English', max_length=200, verbose_name='Name (English)')),
                ('description_en', models.TextField(help_text='Testimonial text in English', verbose_name='Description (English)')),
                ('name_bg', models.CharField(help_text='Име на лице или компания на български', max_length=200, verbose_name='Име (Български)')),
                ('description_bg', models.TextField(help_text='Текст на отзива на български', verbose_name='Описание (Български)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial in slider', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial Card',
                'verbose_name_plural': 'Testimonial Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
