# Generated by Django 5.2.5 on 2025-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0021_testimonialcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_enabled', models.BooleanField(default=True, help_text='Enable/disable API response caching globally', verbose_name='Enable Cache')),
                ('cache_timeout', models.IntegerField(default=1800, help_text='Cache duration in seconds (default: 1800 = 30 minutes)', verbose_name='Cache Timeout (seconds)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache Settings',
                'verbose_name_plural': 'Cache Settings',
            },
        ),
    ]
