# Generated by Django 5.2.5 on 2025-11-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0022_cachesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Our Impact', help_text='Achievements section title in English', max_length=200, verbose_name='Title (English)')),
                ('subtitle_en', models.CharField(default='The numbers speak for themselves', help_text='Achievements section subtitle in English', max_length=200, verbose_name='Subtitle (English)')),
                ('title_bg', models.CharField(default='Нашето въздействие', help_text='Заглавие на achievements секцията на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('subtitle_bg', models.CharField(default='Числата говорят сами за себе си', help_text='Подзаглавие на achievements секцията на български', max_length=200, verbose_name='Подзаглавие (Български)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page - Achievements Header',
                'verbose_name_plural': 'About Page - Achievements Header',
            },
        ),
        migrations.CreateModel(
            name='AboutUsImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_title_en', models.CharField(default='Our Purpose', help_text='Main purpose section title in English', max_length=200, verbose_name='Purpose Title (English)')),
                ('purpose_description_en', models.TextField(default='Empowering businesses with innovative solutions', help_text='Purpose description/subtitle in English', verbose_name='Purpose Description (English)')),
                ('purpose_text_en', models.TextField(help_text='Main purpose text/content in English', verbose_name='Purpose Text (English)')),
                ('purpose_title_bg', models.CharField(default='Нашата цел', help_text='Главно заглавие на секцията на български', max_length=200, verbose_name='Заглавие (Български)')),
                ('purpose_description_bg', models.TextField(default='Даваме възможност на бизнеса с иновативни решения', help_text='Описание/подзаглавие на целта на български', verbose_name='Описание (Български)')),
                ('purpose_text_bg', models.TextField(help_text='Основен текст за целта на български', verbose_name='Текст (Български)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Image - Purpose Content',
                'verbose_name_plural': 'About Us Image - Purpose Content',
            },
        ),
    ]
