# Generated by Django 5.2.5 on 2025-11-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0023_aboutpageachievements_aboutusimagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusimagecontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the background image for the purpose section', max_length=500, null=True, verbose_name='Background Image URL'),
        ),
    ]
