# Generated by Django 5.2.5 on 2026-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_generix', '0024_aboutusimagecontent_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageAchievements',
        ),
        migrations.DeleteModel(
            name='AboutPageHero',
        ),
        migrations.DeleteModel(
            name='AboutUsImageContent',
        ),
        migrations.DeleteModel(
            name='CaseStudySlide',
        ),
        migrations.DeleteModel(
            name='CustomersSection',
        ),
        migrations.DeleteModel(
            name='HomePageCTA',
        ),
        migrations.AlterUniqueTogether(
            name='platformfeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='platformfeature',
            name='platform',
        ),
        migrations.DeleteModel(
            name='PlatformsSectionHeader',
        ),
        migrations.DeleteModel(
            name='WhyGenerixSection',
        ),
        migrations.AlterModelOptions(
            name='aboutustestimonial',
            options={'verbose_name': 'About Us Testimonial', 'verbose_name_plural': 'About Us Testimonial'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Call-to-Action', 'verbose_name_plural': 'Call-to-Actions'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Partner Logo', 'verbose_name_plural': 'Partner Logos'},
        ),
        migrations.AlterModelOptions(
            name='testimonialcard',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_accent',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_accent_hover',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_background',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_background_alt',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_background_secondary',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_border_gray',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_gray_dark',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_gray_light',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_gray_medium',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_hover_cyan',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_hover_indigo',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_hover_pink',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_neutral',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_primary_dark',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_primary_light',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_text',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color_text_dark',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='style',
            field=models.CharField(choices=[('gradient', 'Gradient Background'), ('dark', 'Dark Background'), ('light', 'Light Background')], default='gradient', help_text='Visual style of the CTA section', max_length=20, verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional: Contact phone number', max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='testimonialcard',
            name='role',
            field=models.CharField(blank=True, help_text="Optional: Person's role or company type (e.g., 'Property Investor', 'Real Estate Developer')", max_length=200, verbose_name='Role/Position'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_accent_gold',
            field=models.CharField(default='#c9a84c', help_text='Royal gold accent (e.g., #c9a84c) - Buttons, highlights, borders', max_length=7, verbose_name='Accent Gold'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_accent_gold_hover',
            field=models.CharField(default='#b39440', help_text='Darker gold for hover states (e.g., #b39440)', max_length=7, verbose_name='Gold Hover'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_border',
            field=models.CharField(default='#2a2a2a', help_text='Subtle border for dark theme (e.g., #2a2a2a)', max_length=7, verbose_name='Border Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_overlay',
            field=models.CharField(default='#00000080', help_text='Semi-transparent overlay (e.g., #00000080) - with alpha channel', max_length=9, verbose_name='Overlay Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_primary',
            field=models.CharField(default='#0a0a0a', help_text='Primary dark color (e.g., #0a0a0a) - Deep black for backgrounds', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_surface',
            field=models.CharField(default='#1a1a1a', help_text='Surface color (e.g., #1a1a1a) - Elevated surfaces and cards', max_length=7, verbose_name='Surface Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_text_muted',
            field=models.CharField(default='#6b7280', help_text='Muted text color (e.g., #6b7280) - For labels and captions', max_length=7, verbose_name='Muted Text'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color_text_primary',
            field=models.CharField(default='#ffffff', help_text='Primary text color (e.g., #ffffff) - White for dark backgrounds', max_length=7, verbose_name='Primary Text'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='font_body',
            field=models.CharField(default='Montserrat', help_text="Font family for body text (e.g., 'Montserrat')", max_length=100, verbose_name='Body Font'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='font_heading',
            field=models.CharField(default='Cormorant Garamond', help_text="Font family for headings (e.g., 'Cormorant Garamond')", max_length=100, verbose_name='Heading Font'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='count',
            field=models.CharField(help_text="Display value (e.g., '50+', '€200M+', '5 Countries')", max_length=50, verbose_name='Count/Value'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(help_text="Achievement title in English (e.g., 'Properties Sold', 'Happy Clients')", max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='name',
            field=models.CharField(help_text="Internal name for identification (e.g., 'Home CTA', 'About Page CTA')", max_length=100, verbose_name='CTA Name'),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='address_line1_bg',
            field=models.CharField(default='Луксозен офис комплекс', help_text='Първи ред на адреса на български', max_length=200, verbose_name='Адрес ред 1 (Български)'),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='address_line1_en',
            field=models.CharField(default='Luxury Office Complex', help_text='First line of address in English', max_length=200, verbose_name='Address Line 1 (English)'),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='address_line2_bg',
            field=models.CharField(default='София, България', help_text='Втори ред на адреса на български', max_length=200, verbose_name='Адрес ред 2 (Български)'),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='address_line2_en',
            field=models.CharField(default='Sofia, Bulgaria', help_text='Second line of address in English', max_length=200, verbose_name='Address Line 2 (English)'),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='email',
            field=models.EmailField(default='contact@aurexiaestate.com', help_text='Contact email address', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.CharField(help_text='URL or Angular route (e.g., /properties or https://example.com)', max_length=200, verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='testimonialcard',
            name='description_bg',
            field=models.TextField(help_text='Текст на отзива на български', verbose_name='Отзив (Български)'),
        ),
        migrations.AlterField(
            model_name='testimonialcard',
            name='description_en',
            field=models.TextField(help_text='Testimonial text in English', verbose_name='Testimonial (English)'),
        ),
        migrations.AlterField(
            model_name='testimonialcard',
            name='logo_url',
            field=models.URLField(help_text='URL to company logo or client avatar image', verbose_name='Logo/Avatar URL'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_black',
            field=models.CharField(default='#000000', help_text='Pure black', max_length=7, verbose_name='Black'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_error',
            field=models.CharField(default='#ef4444', help_text='Red for errors', max_length=7, verbose_name='Error Color'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_info',
            field=models.CharField(default='#3b82f6', help_text='Blue for info messages', max_length=7, verbose_name='Info Color'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_success',
            field=models.CharField(default='#10b981', help_text='Green for success messages', max_length=7, verbose_name='Success Color'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_text_secondary',
            field=models.CharField(default='#a0a0a0', help_text='Secondary text color (e.g., #a0a0a0) - Light gray for descriptions', max_length=7, verbose_name='Secondary Text'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_warning',
            field=models.CharField(default='#f59e0b', help_text='Orange for warnings', max_length=7, verbose_name='Warning Color'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color_white',
            field=models.CharField(default='#ffffff', help_text='Pure white', max_length=7, verbose_name='White'),
        ),
        migrations.DeleteModel(
            name='PlatformCard',
        ),
        migrations.DeleteModel(
            name='PlatformFeature',
        ),
    ]
