# Generated by Django 5.2.5 on 2026-02-21 07:22

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text="Destination name in English (e.g., 'Spain', 'Dubai')", max_length=100, unique=True, verbose_name='Name (English)')),
                ('description_en', models.TextField(help_text='Destination description in English', verbose_name='Description (English)')),
                ('short_description_en', models.CharField(help_text='Brief description for cards (max 300 characters)', max_length=300, verbose_name='Short Description (English)')),
                ('name_bg', models.CharField(help_text='Име на дестинацията на български', max_length=100, verbose_name='Име (Български)')),
                ('description_bg', models.TextField(help_text='Описание на дестинацията на български', verbose_name='Описание (Български)')),
                ('short_description_bg', models.CharField(help_text='Кратко описание за карти (максимум 300 символа)', max_length=300, verbose_name='Кратко описание (Български)')),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'spain', 'dubai')", max_length=100, unique=True, verbose_name='Slug')),
                ('hero_image', cloudinary.models.CloudinaryField(help_text='Large hero image for destination page', max_length=255, verbose_name='Hero Image')),
                ('thumbnail_image', cloudinary.models.CloudinaryField(help_text='Thumbnail for destination cards', max_length=255, verbose_name='Thumbnail Image')),
                ('meta_title_en', models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_description_en', models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=300, verbose_name='Meta Description (EN)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured destinations', verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Make destination visible on website', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='InvestorListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Company Address')),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Subscription Status')),
                ('subscription_start', models.DateField(blank=True, null=True, verbose_name='Subscription Start Date')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Subscription End Date')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly subscription fee in EUR', max_digits=10, verbose_name='Monthly Fee (EUR)')),
                ('properties_count', models.IntegerField(default=0, help_text='Number of active properties from this investor', verbose_name='Properties Count')),
                ('notes', models.TextField(blank=True, help_text='Private notes for staff only', verbose_name='Internal Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investor Listing',
                'verbose_name_plural': 'Investor Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text="Feature name in English (e.g., 'Swimming Pool', 'Sea View')", max_length=100, unique=True, verbose_name='Feature Name (English)')),
                ('name_bg', models.CharField(help_text='Име на удобството на български', max_length=100, verbose_name='Име (Български)')),
                ('icon', models.CharField(help_text="Font Awesome class or URL (e.g., 'fa-swimming-pool')", max_length=100, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Property title in English', max_length=300, verbose_name='Title (English)')),
                ('description_en', models.TextField(help_text='Full property description in English', verbose_name='Description (English)')),
                ('short_description_en', models.CharField(help_text='Brief description for cards (max 300 characters)', max_length=300, verbose_name='Short Description (English)')),
                ('title_bg', models.CharField(help_text='Заглавие на имота на български', max_length=300, verbose_name='Заглавие (Български)')),
                ('description_bg', models.TextField(help_text='Пълно описание на имота на български', verbose_name='Описание (Български)')),
                ('short_description_bg', models.CharField(help_text='Кратко описание за карти (максимум 300 символа)', max_length=300, verbose_name='Кратко описание (Български)')),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('penthouse', 'Penthouse'), ('mansion', 'Mansion'), ('apartment', 'Luxury Apartment'), ('estate', 'Estate'), ('chalet', 'Chalet')], default='villa', max_length=50, verbose_name='Property Type')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('price_currency', models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ US Dollar'), ('GBP', '£ Pound Sterling'), ('CHF', 'CHF Swiss Franc')], default='EUR', max_length=3, verbose_name='Currency')),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bathrooms')),
                ('area_sqm', models.DecimalField(decimal_places=2, help_text='Total area in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area (m²)')),
                ('plot_size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Plot/land size in square meters (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plot Size (m²)')),
                ('address', models.CharField(help_text='Property address', max_length=300, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for map', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for map', max_digits=9, null=True, verbose_name='Longitude')),
                ('featured_image', cloudinary.models.CloudinaryField(help_text='Main property image', max_length=255, verbose_name='Featured Image')),
                ('video_url', models.URLField(blank=True, help_text='Optional: YouTube or Vimeo URL', verbose_name='Video URL')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Optional: 360° virtual tour URL', verbose_name='Virtual Tour URL')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=300, unique=True, verbose_name='Slug')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_description_en', models.CharField(blank=True, max_length=300, verbose_name='Meta Description (EN)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured properties', verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Make property visible on website', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times property page was viewed', verbose_name='Views Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When property was published', null=True, verbose_name='Published At')),
                ('destination', models.ForeignKey(help_text='Property destination', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api_aurexia.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeatureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='api_aurexia.propertyfeature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_links', to='api_aurexia.property')),
            ],
            options={
                'verbose_name': 'Property Feature Link',
                'verbose_name_plural': 'Property Feature Links',
                'unique_together': {('property', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', through='api_aurexia.PropertyFeatureLink', to='api_aurexia.propertyfeature', verbose_name='Features'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('caption_en', models.CharField(blank=True, help_text='Optional image caption in English', max_length=200, verbose_name='Caption (English)')),
                ('caption_bg', models.CharField(blank=True, help_text='Опционален надпис на снимката на български', max_length=200, verbose_name='Надпис (Български)')),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_aurexia.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['property', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('message', models.TextField(help_text='Inquiry message from potential buyer', verbose_name='Message')),
                ('budget_range', models.CharField(blank=True, help_text="Optional: buyer's budget range", max_length=100, verbose_name='Budget Range')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Preferred Contact Method')),
                ('is_contacted', models.BooleanField(default=False, help_text='Mark as contacted after follow-up', verbose_name='Contacted')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Contacted At')),
                ('notes', models.TextField(blank=True, help_text='Private notes for staff only', verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='api_aurexia.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['destination', 'status', 'is_active'], name='api_aurexia_destina_c77b03_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'is_active'], name='api_aurexia_is_feat_408a82_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='api_aurexia_slug_b90865_idx'),
        ),
    ]
