# Generated by Django 5.2.5 on 2026-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_aurexia', '0001_initial'),
        ('api_generix', '0025_delete_aboutpageachievements_delete_aboutpagehero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSettingsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cache Settings',
                'verbose_name_plural': 'Cache Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_generix.cachesettings',),
        ),
        migrations.CreateModel(
            name='ContactPageContentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_generix.contactpagecontent',),
        ),
        migrations.CreateModel(
            name='ThemeSettingsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_generix.themesettings',),
        ),
    ]
